spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bike_practice?serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: pengjunxi1208
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
